export const data_test_reports_3 =()=>{
    let obj_data=[
        {
            "date_upload": "8/22/2023 2:51 am",
            "purchase_order_id": "95731",
            "purchase_orders": "Purchase Order #PO-409491696",
            "status_error": false,
            "transaction_statement": "",
            "sender_name": "Curascript",
            "sender_SGLN": "9006477000001",
            "sender_location_name": "Curascript",
            "sender_location_address": "6272 Lee Vista Boulevard, , 32822, Orlando, FL,US",
            "receiver_location_name": "HPG",
            "receiver_location_address": "1330 Industrial Blvd, Suite 200, 77478, Sugar Land, TX,US",
            "shipment_date": "08/18/2023",
            "grouping": "1701",
            "logMessages": "Your EPCIS file has been properly validated.",
            "items_info": [
                {
                    "sgtin": "0355154.094495.40095247428170",
                    "ndc": "00003218713",
                    "product_name": "ABATACEPT/MALTOSE (ORENCIA) 250MG SDV 1/VL",
                    "dosage": "VIAL",
                    "strength": "250MG",
                    "container_size": "1 VL",
                    "lot_number": "1933918",
                    "level_1": "030001.00000000101",
                    "level_2": "",
                    "level_3": "",
                    "trans_hist": []
                },
                {
                    "sgtin": "0355154.094498.40095247428190",
                    "ndc": "57894003001",
                    "product_name": "INFLIXIMAB (REMICADE) 100MG SDV 1EA",
                    "dosage": "VIAL",
                    "strength": "100MG",
                    "container_size": "1 VL",
                    "lot_number": "22MD03761",
                    "level_1": "030001.00000000101",
                    "level_2": "",
                    "level_3": "",
                    "trans_hist": [
                        {
                            "shipment_date": "2020-04-27T17:10:18Z",
                            "sgtin": "0355154.094498.40095247428190",
                            "ndc": "57894003001",
                            "purchase_orders_th": "PO-DIST0056",
                            "product_name": "INFLIXIMAB (REMICADE) 100MG SDV 1EA",
                            "dosage": "VIAL",
                            "strength": "100MG",
                            "container_size": "1 VL",
                            "lot_number": "LOTDISTRIBUIDOR",
                            "level_1": "0355154.094498.40095247428181",
                            "level_2": "",
                            "level_3": "",
                            "sender_name": "",
                            "sender_SGLN": "urn:epc:id:sgln:030124.542688.0",
                            "sender_street_addr1": "",
                            "sender_street_addr2": "",
                            "sender_city": "",
                            "sender_state": "",
                            "sender_postalCode": "",
                            "sender_countryCode": "",
                            "sender_loc_name": "",
                            "sender_loc_street_addr1": "",
                            "sender_loc_street_addr2": "",
                            "sender_loc_city": "",
                            "sender_loc_state": "",
                            "sender_loc_postalCode": "",
                            "sender_loc_countryCod": "",
                            "receiver_name": "GS1 Pharma LLC",
                            "receiver_SGLN": "urn:epc:id:sgln:030001.111124.0",
                            "receiver_street_addr1": "1295 S George Ave",
                            "receiver_street_addr2": "Room 378",
                            "receiver_city": "Washington",
                            "receiver_state": "DC",
                            "receiver_postalCode": "US",
                            "receiver_countryCode": "US",
                            "receiver_loc_name": "GS1 Pharma LLC",
                            "receiver_loc_street_addr1": "1299 S George Ave",
                            "receiver_loc_street_addr2": "Room 378",
                            "receiver_loc_city": "Washington",
                            "receiver_loc_state": "DC",
                            "receiver_loc_postalCode": "12345-6789",
                            "receiver_loc_countryCode": "US"
                        }
                    ]
                },
                {
                    "sgtin": "0355154.094498.40095247428191",
                    "ndc": "57894003001",
                    "product_name": "INFLIXIMAB (REMICADE) 100MG SDV 1EA",
                    "dosage": "VIAL",
                    "strength": "100MG",
                    "container_size": "1 VL",
                    "lot_number": "22MD03761",
                    "level_1": "030001.00000000101",
                    "level_2": "",
                    "level_3": "",
                    "trans_hist": [
                        {
                            "shipment_date": "2020-04-27T17:10:18Z",
                            "sgtin": "0355154.094498.40095247428191",
                            "ndc": "57894003001",
                            "purchase_orders_th": "PO-DIST0056",
                            "product_name": "INFLIXIMAB (REMICADE) 100MG SDV 1EA",
                            "dosage": "VIAL",
                            "strength": "100MG",
                            "container_size": "1 VL",
                            "lot_number": "LOTDISTRIBUIDOR",
                            "level_1": "0355154.094498.40095247428181",
                            "level_2": "",
                            "level_3": "",
                            "sender_name": "",
                            "sender_SGLN": "urn:epc:id:sgln:030124.542688.0",
                            "sender_street_addr1": "",
                            "sender_street_addr2": "",
                            "sender_city": "",
                            "sender_state": "",
                            "sender_postalCode": "",
                            "sender_countryCode": "",
                            "sender_loc_name": "",
                            "sender_loc_street_addr1": "",
                            "sender_loc_street_addr2": "",
                            "sender_loc_city": "",
                            "sender_loc_state": "",
                            "sender_loc_postalCode": "",
                            "sender_loc_countryCod": "",
                            "receiver_name": "GS1 Pharma LLC",
                            "receiver_SGLN": "urn:epc:id:sgln:030001.111124.0",
                            "receiver_street_addr1": "1295 S George Ave",
                            "receiver_street_addr2": "Room 378",
                            "receiver_city": "Washington",
                            "receiver_state": "DC",
                            "receiver_postalCode": "US",
                            "receiver_countryCode": "US",
                            "receiver_loc_name": "GS1 Pharma LLC",
                            "receiver_loc_street_addr1": "1299 S George Ave",
                            "receiver_loc_street_addr2": "Room 378",
                            "receiver_loc_city": "Washington",
                            "receiver_loc_state": "DC",
                            "receiver_loc_postalCode": "12345-6789",
                            "receiver_loc_countryCode": "US"
                        }
                    ],
                    "receipts":[
                        {
                            "tranid": "Item Receipt #IR-000101",
                            "item": "57894003001",
                            "quantity": "5",
                            "trandate": "08/21/2023",
                            "recordtype": "Item Receipt",
                            "sender_location_address": "6272 Lee Vista Boulevard, , 32822, Orlando, FL,US",
                            "receiver_location_address": "1330 Industrial Blvd, Suite 200, 77478, Sugar Land, TX,US",
                            "product_name": "INFLIXIMAB (REMICADE) 100MG SDV 1EA",
                            "dosage": "Vial",
                            "strength": "100MG",
                            "container_size": "1"
                        },
                        {
                            "tranid": "Item Receipt #IR-000101",
                            "item": "57894003001",
                            "quantity": "10",
                            "trandate": "08/21/2023",
                            "recordtype": "Item Receipt",
                            "sender_location_address": "6272 Lee Vista Boulevard, , 32822, Orlando, FL,US",
                            "receiver_location_address": "1330 Industrial Blvd, Suite 200, 77478, Sugar Land, TX,US",
                            "product_name": "INFLIXIMAB (REMICADE) 100MG SDV 1EA",
                            "dosage": "Vial",
                            "strength": "100MG",
                            "container_size": "1"
                        },
                        {
                            "tranid": "Item Receipt #IR-000101",
                            "item": "57894003001",
                            "quantity": "",
                            "trandate": "08/21/2023",
                            "recordtype": "Item Receipt",
                            "sender_location_address": "6272 Lee Vista Boulevard, , 32822, Orlando, FL,US",
                            "receiver_location_address": "1330 Industrial Blvd, Suite 200, 77478, Sugar Land, TX,US",
                            "product_name": "INFLIXIMAB (REMICADE) 100MG SDV 1EA",
                            "dosage": "Vial",
                            "strength": "100MG",
                            "container_size": "1"
                        },
                        {
                            "tranid": "Item Receipt #IR-000101",
                            "item": "57894003001",
                            "quantity": "20",
                            "trandate": "08/21/2023",
                            "recordtype": "Item Receipt",
                            "sender_location_address": "6272 Lee Vista Boulevard, , 32822, Orlando, FL,US",
                            "receiver_location_address": "1330 Industrial Blvd, Suite 200, 77478, Sugar Land, TX,US",
                            "product_name": "INFLIXIMAB (REMICADE) 100MG SDV 1EA",
                            "dosage": "Vial",
                            "strength": "100MG",
                            "container_size": "1"
                        },
                        {
                            "tranid": "Item Receipt #IR-000102",
                            "item": "57894003001",
                            "quantity": "",
                            "trandate": "08/18/2023",
                            "recordtype": "Item Receipt",
                            "sender_location_address": "6272 Lee Vista Boulevard, , 32822, Orlando, FL,US",
                            "receiver_location_address": "1330 Industrial Blvd, Suite 200, 77478, Sugar Land, TX,US",
                            "product_name": "INFLIXIMAB (REMICADE) 100MG SDV 1EA",
                            "dosage": "Vial",
                            "strength": "100MG",
                            "container_size": "1"
                        },
                        {
                            "tranid": "Item Receipt #IR-000102",
                            "item": "57894003001",
                            "quantity": "2",
                            "trandate": "08/18/2023",
                            "recordtype": "Item Receipt",
                            "sender_location_address": "6272 Lee Vista Boulevard, , 32822, Orlando, FL,US",
                            "receiver_location_address": "1330 Industrial Blvd, Suite 200, 77478, Sugar Land, TX,US",
                            "product_name": "INFLIXIMAB (REMICADE) 100MG SDV 1EA",
                            "dosage": "Vial",
                            "strength": "100MG",
                            "container_size": "1"
                        },
                        {
                            "tranid": "Item Receipt #IR-000102",
                            "item": "57894003001",
                            "quantity": "2",
                            "trandate": "08/18/2023",
                            "recordtype": "Item Receipt",
                            "sender_location_address": "6272 Lee Vista Boulevard, , 32822, Orlando, FL,US",
                            "receiver_location_address": "1330 Industrial Blvd, Suite 200, 77478, Sugar Land, TX,US",
                            "product_name": "INFLIXIMAB (REMICADE) 100MG SDV 1EA",
                            "dosage": "Vial",
                            "strength": "100MG",
                            "container_size": "1"
                        },
                        {
                            "tranid": "Item Receipt #IR-000102",
                            "item": "57894003001",
                            "quantity": "1",
                            "trandate": "08/18/2023",
                            "recordtype": "Item Receipt",
                            "sender_location_address": "6272 Lee Vista Boulevard, , 32822, Orlando, FL,US",
                            "receiver_location_address": "1330 Industrial Blvd, Suite 200, 77478, Sugar Land, TX,US",
                            "product_name": "INFLIXIMAB (REMICADE) 100MG SDV 1EA",
                            "dosage": "Vial",
                            "strength": "100MG",
                            "container_size": "1"
                        }
                    ]
                },
                {
                    "sgtin": "0355154.094499.40095247428180",
                    "ndc": "57894035001",
                    "product_name": "GOLIMUMAB (SIMPONI ARIA) 50MG SDV 1EA",
                    "dosage": "VIAL",
                    "strength": "50MG",
                    "container_size": "1 VL",
                    "lot_number": "MJS3902",
                    "level_1": "030001.00000000101",
                    "level_2": "",
                    "level_3": "",
                    "trans_hist": []
                },
                {
                    "sgtin": "0355154.094499.40095247428181",
                    "ndc": "57894035001",
                    "product_name": "GOLIMUMAB (SIMPONI ARIA) 50MG SDV 1EA",
                    "dosage": "VIAL",
                    "strength": "50MG",
                    "container_size": "1 VL",
                    "lot_number": "MJS3902",
                    "level_1": "030001.00000000101",
                    "level_2": "",
                    "level_3": "",
                    "trans_hist": []
                }
            ],
           
        }
        
    ];
    return obj_data;
}