export const data_test_reports_2 = () => {
    let data = [
        {
            containerSize: "500 pills",
            dosage: "PILL",
            epcisFile: "55037",
            expirationDate: "2025-03-30",
            isInQuarantine: false,
            isThFromFile: false,
            item: "10017",
            level1: "urn:epc:id:sscc:030001.00000000101",
            level2: "",
            level3: "",
            lotIsSuspicious: false,
            lotLocation: "HPG",
            lotNumber: "B5014B01",
            manufacturertraderName: "GS1 Pharma LLC",
            productName: "TOCILIZUMAB (ACTEMRA) 80MG/4ML SDV 1EA",
            receiverCity: "New York",
            receiverCountryCode: "US",
            receiverLocationAddressOne: "231 Park Ave S",
            receiverLocationAddressTwo: "Room 378",
            receiverLocationCity: "New York",
            receiverLocationCountryCode: "US",
            receiverLocationName: "GS1 Drug Distro LLC",
            receiverLocationPostalCode: "10003-1502",
            receiverLocationState: "NY",
            receiverName: "GS1 Drug Distro LLC",
            receiverOfLocationSgln: "urn:epc:id:sgln:039999.999928.0",
            receiverSgln: "urn:epc:id:sgln:039999.999929.0",
            receiverState: "NY",
            receiverStreetAddressOne: "230 Park Ave S",
            receiverStreetAddressTwo: "Room 378",
            senderCity: "Washington",
            senderCountryCode: "US",
            senderLocationAddressOne: "1299 S George Ave",
            senderLocationAddressTwo: "Room 378",
            senderLocationCity: "Washington",
            senderLocationCountryCode: "US",
            senderLocationName: "GS1 Pharma LLC",
            senderLocationPostalCode: "12345-6789",
            senderLocationState: "DC",
            senderName: "GS1 Pharma LLC",
            senderOfLocationSgln: "urn:epc:id:sgln:030001.111125.0",
            senderPostalCode: "12345-6789",
            senderSgln: "urn:epc:id:sgln:030001.111124.0",
            senderState: "DC",
            senderStreetAddressOne: "1295 S George Ave",
            senderStreetAddressTwo: "Room 378",
            shipmentDate: "2020-03-27T17:10:18Z",
            strength: "100mg",
            suitetraceGrouping: "903",
            transactionInformationIdRelated: "",
            transactionStatement: "Seller has complied with each applicable subsection of FDCA Sec. 581(27)(A)-(G).",
            transaction_id: "95731",
            transaction_po: "Purchase Order #PO-409491696"
        }
    ];
    return data;
}